---
- hosts: vpn
  become: true
  remote_user: ubuntu
  vars_files:
    - vars/main.yml
  tasks:
    - name: Install Docker Module for Python
      pip: name="{{item}}" state=latest
      loop: ['docker-py', 'pexpect']

    - name: Ensure openvpn config is generated
      command: docker run -v {{openvpn_data_volume}}:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u tcp://vpn.{{domain}}:443

    - name: "Generate PKI"
      expect:
        command: docker run -v {{openvpn_data_volume}}:/etc/openvpn --rm -it {{openvpn_docker_image}} ovpn_initpki
        timeout: 300
        responses:
          "Enter New CA Key Passphrase": "{{openvpn_pki_pass}}"
          "Re-Enter New CA Key Passphrase": "{{openvpn_pki_pass}}"
          "Common Name": "{{public_domain}}"
          "Enter pass phrase for /etc/openvpn/pki/private/ca.key:": "{{openvpn_pki_pass}}"

    - name: Ensure client keys are generated
      expect:
        command: "docker run -v {{openvpn_data_volume}}:/etc/openvpn --rm -it {{openvpn_docker_image}} easyrsa build-client-full {{item}} nopass"
        responses:
          "Enter pass phrase": "{{openvpn_pki_pass}}"
      with_items: "{{openvpn_clients}}"

    - name: Save generated keys
      shell: docker run -v "{{openvpn_data_volume}}:/etc/openvpn" --rm "{{openvpn_docker_image}}" ovpn_getclient {{item}} > /root/{{item}}.ovpn
      with_items: "{{openvpn_clients}}"

    - name: Fetch clients
      fetch: src=/root/{{item}}.ovpn  dest=/home/{{user}}/vpn-ca/ flat=yes
      with_items:
        - "{{openvpn_clients}}"



 # docker run -v /ovpn-data:/etc/openvpn --rm -it kylemanna/openvpn ovpn_genconfig ovpn_initpki
